#!/bin/bash

#OpenStack config
export OS_TENANT_NAME=kyprivate
export OS_USERNAME=kyprivate
export OS_PASSWORD=kyprivate2014
export OS_AUTH_URL="http://203.130.40.133:5000/v2.0/"

KYWEB_MAJOR_VERSION="0.0."
PLATFORM_MAJOR_VERSION="0.1."
RETRY_TIMEOUT='60' 			#minutes to configure one config instance
WAIT_FOR_PING_REPLY='1' 		#minutes
PING_RETRY_INTERVAL='5' 		#DEFAULT 5 seconds ; must be under 60 seconds
NOVA_RETRY_INTERVAL='30' 		#DEFAULT 30 seconds ; must be greater than nova list command response time ; must be under 60 seconds
MONGO_PROCCES_UPTIME='5'  	#seconds till mongo start
TIMEOUT='1'					#minutes for an instance to get in Running mode 
SHORT_RETRY_INTERVAL='10' 	#DEFAULT 10 seconds ; must be greater than nova list command response time ; must be under 60 seconds
RETRY='0'						#Number of retries to create an instance
RETRY_INDEX='0' 				#index of retry
MONGO_INITIATE_UPTIME='30'	#seconds till rs.initiate raise the status to primary

LB_WEB_FLOATING_IP_1='203.130.40.150'
LB_WEB_FLOATING_IP_2='203.130.40.151'
MAIN_PROXY_FLOATING_IP_1='203.130.40.152'
MAIN_PROXY_FLOATING_IP_2='203.130.40.153'
BASP_PROXY_FLOATING_IP='203.130.40.157'
ADMIN_PROXY_FLOATING_IP='203.130.40.158'
CLOUD_ADMIN_SERVER="203.130.40.156"

CLOUD_ADMIN_SERVER_LOCAL_IP="172.24.0.11"

KYDEV_USER='kydev'
KYDEV_PASSWD='WmxtcF7h'
KEYSTORE_LOCATION='/etc/ssl/certs/'
LOG_FILE='/var/log/cloud-install.log'
BASE_URL='base.url = https://www.che001.com'
API_CORE_VOLUME='efab4049-0c11-4653-a262-793c728d2974'
CHE001_MAIL="####che001 mail####
ky.core.common.system.email=che001@che001.com
mail.smtp.host=mail.che001.com
mail.smtp.port=25
mail.smtp.socketFactory.port=25
mail.debug=true
mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.from=che001@che001.com
mail.username=che001@che001.com
mail.password=kaiyuan2014"
SENDCLOUD_MAIL="####senbcloud mail####
ky.core.common.system.email=che001@che001.com
mail.smtp.host=smtpcloud.sohu.com
mail.smtp.port=25
mail.smtp.socketFactory.port=25
mail.debug=true
mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.from=postmaster@che001.sendcloud.org
mail.username=postmaster@che001.sendcloud.org
mail.password=9E6Ov2zKBExzAGsd"
LOCAL_MAIL="####local mail####
ky.core.common.system.email=che001@che001.com
mail.smtp.host=mail.stg-che001.com
mail.smtp.port=25
mail.smtp.socketFactory.port=25
mail.debug=true
mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.from=che001@mail.stg-che001.com
mail.username=che001@mail.stg-che001.com
mail.password=kaiyuan2014"
MAIL_PROPERTIES=$SENDCLOUD_MAIL
SPECIAL_ROLES_PARENT_ID='00000000-0000-3000-8000-000000000001'

SCHEDULERS_HOUR_OF_DAY='2'

##########BASP config##########
BASP_PUBLIC_IP='121.28.7.101'
BASP_PORT='8989'
BASP_HOSTNAME='basp.che001.com'
API_BASP_CERT='keyC_v4.jks'
API_BASP_TRUST_CERT='trustedRootCA.jks'
BASP_KEYSTORE=$KEYSTORE_LOCATION$API_BASP_CERT
BASP_KEYSTORE_PASS='devops2013'
BASP_TRUSTSTORE=$KEYSTORE_LOCATION$API_BASP_TRUST_CERT
BASP_TRUSTSTORE_PASS='devops2013'

##########NOVA BOOT OPTIONS##########
API_FLAVOR='5'
CORE_FLAVOR='5'
SOLR_FLAVOR='5'
MAIN_PROXY_FLAVOR='5'
BASP_PROXY_FLAVOR='5'
ADMIN_PROXY_FLAVOR='5'
REDIS_FLAVOR='5'
MONGO_FLAVOR='2'
MYSQL_FLAVOR='2'
RABBITMQ_FLAVOR='5'
MONGO_CONFIG_FLAVOR='5'
WEBUI_FLAVOR='5'
LBWEB_FLAVOR='5'

API_IMAGE='CentOS65_27092014_V6'
CORE_IMAGE='CentOS65_27092014_V6'
SOLR_IMAGE='CentOS65_27092014_V6'
MAIN_PROXY_IMAGE='CentOS65_27092014_V6'
BASP_PROXY_IMAGE='CentOS65_27092014_V6'
ADMIN_PROXY_IMAGE='CentOS65_27092014_V6'
REDIS_IMAGE='CentOS65_27092014_V6'
RABBITMQ_IMAGE='CentOS65_27092014_V6'
MONGO_IMAGE='CentOS65_27092014_V6'
MYSQL_IMAGE='CentOS65_27092014_V6'
MONGO_CONFIG_IMAGE='CentOS65_27092014_V6'
WEBUI_IMAGE='CentOS65_27092014_V6'
LBWEB_IMAGE='CentOS65_27092014_V6'

API_SECURITY_GROUP='api-sec-group'
CORE_SECURITY_GROUP='core-sec-group'
SOLR_SECURITY_GROUP='solr-sec-group'
MAIN_PROXY_SECURITY_GROUP='mainproxy-sec-group'
BASP_PROXY_SECURITY_GROUP='baspproxy-sec-group'
ADMIN_PROXY_SECURITY_GROUP='adminproxy-sec-group'
REDIS_SECURITY_GROUP='redis-sec-group'
RABBITMQ_SECURITY_GROUP='rabbitmq-sec-group'
MONGO_SECURITY_GROUP='mongo-sec-group'
MYSQL_SECURITY_GROUP='mysql-sec-group'
MONGO_CONFIG_SECURITY_GROUP='mongo-sec-group'
WEBUI_SECURITY_GROUP='webui-sec-group'
REPOSITORY_SECURITY_GROUP='repository-sec-group'
ADMINSERVER_SECURITY_GROUP='adminserver-sec-group'
LBWEB_SECURITY_GROUP='lbweb-sec-group'
ZABBIX_SECURITY_GROUP='zabbix-sec-group'

API_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
CORE_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
SOLR_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
MAIN_PROXY_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
BASP_PROXY_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
ADMIN_PROXY_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
REDIS_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
RABBITMQ_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
MONGO_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
MYSQL_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
MONGO_CONFIG_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
WEBUI_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'
LBWEB_NET_ID='3d31b386-991e-452e-bcd0-5545669dbcab'

KEY_NAME='cloud_admin_key'

##########Constants##########
#INSTANCE TYPES GENERIC NAMES
LOCAL_REPO='172.24.0.12'
PRIVATE_KEY_FILE='keys.dat'
PORT_USER='10001'
PORT_COMPANY='11001'
PORT_BANKING='12001'
PORT_MESSAGING='13001'
PORT_FILE='14001'
PORT_BACKEND='15001'
PORT_ENCRYPTION='17001'
PORT_ENGINE='18001'
PORT_TRANSACTION='19001'

#Ethernet inferface
DEFAULT_ETH='0'

#LB_WEB_GENERIC 
LB_WEB_GENERIC='lb-web'
LB_WEB_STATIC_IP1='172.24.0.205'
LB_WEB_STATIC_IP2='172.24.0.206'

#INSTANCE TYPES GENERIC NAMES
CORE_USER_GENERIC='core-user'
CORE_COMPANY_GENERIC='core-company'
CORE_ENGINE_GENERIC='core-engine'
CORE_MESSAGING_GENERIC='core-messaging'
CORE_FILE_GENERIC='core-file'
CORE_ENCRYPTION_GENERIC='core-encryption'
CORE_BANKING_GENERIC='core-banking'
CORE_TRANSACTION_GENERIC='core-transaction'
CORE_BACKEND_GENERIC='core-backend'

API_USER_GENERIC='api-user'
API_COMPANY_GENERIC='api-company'
API_SEARCH_GENERIC='api-search'
API_SUPPORT_GENERIC='api-support'
API_AUTH_GENERIC='api-auth'
API_BANKING_GENERIC='api-banking'
API_TRANSACTION_GENERIC='api-transaction'
API_BACKEND_GENERIC='api-backend'
API_BASP_GENERIC='api-basp'

WEBUI_GENERIC='webui'

PROPAGANDA_GENERIC='propaganda'

#MAIN PROXY GENERIC
MAIN_PROXY_GENERIC='main-proxy'
MAIN_PROXY_DOMAIN='che001.com'
MAIN_PROXY_STATIC_IP1='172.24.0.207'
MAIN_PROXY_STATIC_IP2='172.24.0.208'

#BASP PROXY GENERIC
BASP_PROXY_GENERIC='basp-proxy'
BASP_PROXY_STATIC_IP1='172.24.0.209'
BASP_PROXY_STATIC_IP2='172.24.0.210'

#ADMIN PROXY GENERIC
ADMIN_PROXY_GENERIC='admin-proxy'
ADMIN_PROXY_STATIC_IP1='172.24.0.211'

ZABBIX_PORT='10051'

LB_SUBNET_ID='1a9b3f11-aa03-45fc-9b7e-05775ac79940'
AUTH_LB_IP='172.24.0.232'
USER_LB_IP='172.24.0.233'
BANKING_LB_IP='172.24.0.234'
BACKEND_LB_IP='172.24.0.235'
COMPANY_LB_IP='172.24.0.236'
TRANSACTION_LB_IP='172.24.0.237'
SEARCH_LB_IP='172.24.0.238'
SUPPORT_LB_IP='172.24.0.239'
ZABBIX_SERVER='172.24.0.217'
WEBUI_LB_IP='172.24.0.241'

BASP_LB_IP='172.24.0.242'
RABBITMQ_LB_IP='172.24.0.243'

#DB configuration
MONGO_VOLUME_SIZE=200
MYSQL_VOLUME_SIZE=200

MYSQL_SERVER='172.24.0.220'
MYSQL_STATIC_IP1='172.24.0.220'
MYSQL_STATIC_IP2='172.24.0.221'
MYSQL_SERVER_GENERIC='mysql'
MYSQL_PORT='3306'

MONGOS_SERVER='localhost'
MONGOS_PORT='27020'
MONGOD_STATIC_IP1='172.24.0.222'
MONGOD_STATIC_IP2='172.24.0.223'
MONGOD_STATIC_IP3='172.24.0.224'
MONGOD_STATIC_IP4='172.24.0.225'
MONGOC_STATIC_IP1='172.24.0.226'
MONGOC_STATIC_IP2='172.24.0.227'
MONGOC_STATIC_IP3='172.24.0.228'

CORE_USER_MONGO_DBNAME='che001'
CORE_USER_MONGO_USER='platform'
CORE_USER_MONGO_PASS='che0012014'
CORE_USER_MYSQL_DBNAME='che001'
CORE_USER_MYSQL_USER='platform'
CORE_USER_MYSQL_PASS='che0012014'

CORE_FILE_MONGO_DBNAME='che001'
CORE_FILE_MONGO_USER='platform'
CORE_FILE_MONGO_PASS='che0012014'
CORE_FILE_MYSQL_DBNAME='che001'
CORE_FILE_MYSQL_USER='platform'
CORE_FILE_MYSQL_PASS='che0012014'

CORE_BANKING_MONGO_DBNAME='che001'
CORE_BANKING_MONGO_USER='platform'
CORE_BANKING_MONGO_PASS='che0012014'
CORE_BANKING_MYSQL_DBNAME='che001'
CORE_BANKING_MYSQL_USER='platform'
CORE_BANKING_MYSQL_PASS='che0012014'

CORE_COMPANY_MONGO_DBNAME='che001'
CORE_COMPANY_MONGO_USER='platform'
CORE_COMPANY_MONGO_PASS='che0012014'
CORE_COMPANY_MYSQL_DBNAME='che001'
CORE_COMPANY_MYSQL_USER='platform'
CORE_COMPANY_MYSQL_PASS='che0012014'

CORE_ENGINE_MONGO_DBNAME='che001'
CORE_ENGINE_MONGO_USER='platform'
CORE_ENGINE_MONGO_PASS='che0012014'
CORE_ENGINE_MYSQL_DBNAME='che001'
CORE_ENGINE_MYSQL_USER='platform'
CORE_ENGINE_MYSQL_PASS='che0012014'

CORE_MESSAGING_MONGO_DBNAME='che001'
CORE_MESSAGING_MONGO_USER='platform'
CORE_MESSAGING_MONGO_PASS='che0012014'
CORE_MESSAGING_MYSQL_DBNAME='che001'
CORE_MESSAGING_MYSQL_USER='platform'
CORE_MESSAGING_MYSQL_PASS='che0012014'

CORE_TRANSACTION_MONGO_DBNAME='che001'
CORE_TRANSACTION_MONGO_USER='platform'
CORE_TRANSACTION_MONGO_PASS='che0012014'
CORE_TRANSACTION_MYSQL_DBNAME='che001'
CORE_TRANSACTION_MYSQL_USER='platform'
CORE_TRANSACTION_MYSQL_PASS='che0012014'

CORE_BACKEND_MONGO_DBNAME='che001'
CORE_BACKEND_MONGO_USER='platform'
CORE_BACKEND_MONGO_PASS='che0012014'
CORE_BACKEND_MYSQL_DBNAME='che001'
CORE_BACKEND_MYSQL_USER='platform'
CORE_BACKEND_MYSQL_PASS='che0012014'

#MONGO CONFIGURATION PARAMETERS
MONGOS='mongos-instance'
MONGOS_CONFIGDB=''
MONGOS_LOGPATH_DIR='/dbfiles/mongos/'
MONGOS_LOGPATH=$MONGOS_LOGPATH_DIR'mongos0.log'
MONGOS_FORK='true'
MONGOS_LOGAPPEND='true'
MONGOS_BINDIP=''

#TYPE DATABASE
MONGOD_DATABASE='mongod-database'
MONGOD_DATABASE_DBPATH='/dbfiles/data/mongo/'
MONGOD_DATABASE_LOGPATH_DIR='/dbfiles/log/'
MONGOD_DATABASE_LOGPATH=$MONGOD_DATABASE_LOGPATH_DIR'mongod.log'
MONGOD_DATABASE_PORT='27017'
MONGOD_DATABASE_BIND_IP=''
MONGOD_DATABASE_FORK='true'
MONGOD_DATABASE_SHARDSVR='true'
MONGOD_DATABASE_SMALL_FILES='false'
MONGOD_DATABASE_OP_LOGSIZE='5120'
MONGOD_DATABASE_ADMIN='admin'
MONGOD_DATABASE_ADMIN_USER='MongoAdmin'
MONGOD_DATABASE_ADMIN_PASS='secret'
MONGOD_DATABASE_LOGAPPEND='true'

#TYPE CONFIG
MONGOD_CONFIG='mongod-config'
MONGOD_CONFIG_DBPATH='/dbfiles/configdb/'
MONGOD_CONFIG_LOGPATH_DIR='/dbfiles/configdb/'
MONGOD_CONFIG_LOGPATH=$MONGOD_CONFIG_LOGPATH_DIR'cfg.log'
MONGOD_CONFIG_ADMIN='config'
MONGOD_CONFIG_FORK='true'
MONGOD_CONFIG_LOGAPPEND='true'
MONGOD_CONFIG_PORT='27019'
MONGOD_CONFIG_BINDIP=''
MONGOD_CONFIG_CONFIGSVR='true'
MONGOD_CONFIG_SMALLFILES='true'

MONGO_AUTH='true'
MONGO_KEY_DIR='/dbfiles/'
MONGO_KEY=$MONGO_KEY_DIR'mongo_auth_key'

#WEBUI
WEBUI_SERVER_GENERIC='webui'

#SOLR
TOMCAT_VERSION='7.0.52'
TOMCAT_HOME='/usr/share/tomcat/latest'


SOLR_VERSION='4.6.1'
SOLR_HOME='/usr/local/solr/latest'

SOLR_VOLUME_SIZE=100
SOLR_SERVER_GENERIC='solr'
SOLR_SERVER=''
SOLR_PORT='8080'
SOLR_STATIC_IP1='172.24.0.200'
SOLR_STATIC_IP2='172.24.0.203'
SOLR_CONSOLE=$SOLR_STATIC_IP1

#RABBITMQ
################DEPRECATED################
RABBITMQ_EPEL='http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm'
RABBITMQ_ERLANG='http://repos.fedorapeople.org/repos/peter/erlang/epel-erlang.repo'
RABBITMQ_URL='http://www.rabbitmq.com/rabbitmq-signing-key-public.asc'
################DEPRECATED################
RABBITMQ_ERLANG_RPM='esl-erlang'
RABBITMQ_ERLANG_COMPAT_RPM='esl-erlang-compat'
RABBITMQ_RPM='rabbitmq-server'
RABBITMQ_SERVER=''
RABBITMQ_PORT='5672'
RABBITMQ_USER='kaiyuan'
RABBITMQ_PASSWD='kaiyuan2014'
RABBITMQ_SERVER_GENERIC='rabbitmqMS'
RABBITMQ_STATIC_IP1='172.24.0.201'
RABBITMQ_STATIC_IP2='172.24.0.202'
RABBIMQ_CONSOLE=$RABBITMQ_STATIC_IP1

#Redis
REDIS_VERSION='2.8.13'
REDIS_GZIP='redis-'$REDIS_VERSION'.tar.gz'
REDIS_URL='http://download.redis.io/releases/'$REDIS_GZIP
REDIS_HOME='/usr/local/redis/latest'
REDIS_SERVER_GENERIC='redisCluster'
REDIS_STATIC_IP1='172.24.0.7'
REDIS_STATIC_IP2='172.24.0.68'
REDIS_STATIC_IP3='172.24.0.69'
REDIS_PORT='6379'
REDIS_SENTINEL_PORT='26379'
REDIS_MASTER_IP=$REDIS_STATIC_IP1


#MYSQL
MYSQL_URL='http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm'
MYSQL_RPM='mysql-community-release-el6-5.noarch.rpm'
MYSQL_DBPATH='/dbfiles'
MYSQL_DBPATH_DATA="$MYSQL_DBPATH/data"
MYSQL_DBPATH_TMP="$MYSQL_DBPATH/temp"
MYSQL_DBPATH_UNDO="$MYSQL_DBPATH/undologs"

APACHE_HOME='/usr/local/apache2'

############Health monitors############
LB_HTTP_HEALTH_MONITOR='57a4fe7d-a518-4fbf-85bc-c9dc1cf9ffd3'
LB_HTTPS_HEALTH_MONITOR='2abef954-5772-4902-aeac-b7d19152af75'
LB_PING_HEALTH_MONITOR='ded96532-197e-4b71-a7c0-e5aed4111f09'

############MEMBER PORTS############
PORT_HTTPS_API_USER='4430'
PORT_HTTPS_API_AUTH='4431'
PORT_HTTPS_API_BASP='4432'
PORT_HTTPS_API_SEARCH='4433'
PORT_HTTPS_API_COMPANY='4434'
PORT_HTTPS_API_BANKING='4435'
PORT_HTTPS_API_SUPPORT='4436'
PORT_HTTPS_API_TRANSACTION='4437'
PORT_HTTPS_API_BACKEND='4439'
PORT_HTTP_ANDROID_PROMO='81'
PORT_HTTP_PROPAGANDA='82'
PORT_HTTPS_WEBUI='443'

PORT_HTTP_API_USER='9000'
PORT_HTTP_API_AUTH='9001'
PORT_HTTP_API_BASP='9002'
PORT_HTTP_API_SEARCH='9003'
PORT_HTTP_API_COMPANY='9004'
PORT_HTTP_API_BANKING='9005'
PORT_HTTP_API_SUPPORT='9006'
PORT_HTTP_API_TRANSACTION='9007'
PORT_HTTP_API_BACKEND='9009'
PORT_HTTP_WEBUI='80'

############Load Balancers names############
LB_HTTP_AndroidPromo='androidPromo_lb'
LB_HTTP_PROPAGANDA='propaganda_lb'

LB_HTTPS_API_USER='https_user_lb'
LB_HTTPS_API_AUTH='https_auth_lb'
LB_HTTPS_API_BANKING='https_banking_lb'
LB_HTTPS_API_COMPANY='https_company_lb'
LB_HTTPS_API_SUPPORT='https_support_lb'
LB_HTTPS_API_SEARCH='https_search_lb'
LB_HTTPS_API_TRANSACTION='https_transaction_lb'
LB_HTTPS_API_BACKEND='https_backend_lb'
LB_HTTPS_API_BASP='https_basp_lb'
LB_HTTPS_WEB_UI='https_webui_lb'

LB_HTTP_API_BASP='http_basp_lb'
LB_HTTP_API_USER='http_user_lb'
LB_HTTP_API_AUTH='http_auth_lb'
LB_HTTP_API_BANKING='http_banking_lb'
LB_HTTP_API_COMPANY='http_company_lb'
LB_HTTP_API_SUPPORT='http_support_lb'
LB_HTTP_API_SEARCH='http_search_lb'
LB_HTTP_API_TRANSACTION='http_transaction_lb'
LB_HTTP_API_BACKEND='http_backend_lb'
LB_HTTP_WEB_UI='http_webui_lb'

LB_TCP_RABBITMQ='tcp_rabbitmq_lb'

############Zabbix############
ZABBIX_USER="zabbixScript"
ZABBIX_PASS="6Z7RBZhch7L6asi"
ZABBIX_API="http://$ZABBIX_SERVER/zabbix/api_jsonrpc.php"

############Load Balancers vip floating ips############
HTTP_PROPAGANDA_FLOATING_IP=''
HTTP_ANDROID_PROMO_FLOATING_IP=''

HTTPS_API_USER_FLOATING_IP=''
HTTPS_API_AUTH_FLOATING_IP=''
HTTPS_API_COMPANY_FLOATING_IP=''
HTTPS_API_BANKING_FLOATING_IP=''
HTTPS_API_SEARCH_FLOATING_IP=''
HTTPS_API_SUPPORT_FLOATING_IP=''
HTTPS_API_TRANSACTION_FLOATING_IP=''
HTTPS_API_BACKEND_FLOATING_IP=''
HTTPS_API_BASP_FLOATING_IP=''
HTTPS_WEBUI_FLOATING_IP=''

#SWIFT FILES
SWIFT_DIC_FILE='dic.tar.gz'
SWIFT_DIC_WORDS_FILE='dic_words.tar.gz'
SWIFT_TOMCAT_FILE='apache-tomcat-7.0.52.tar.gz'
SWIFT_SOLR_FILE='solr-4.6.1.tgz'
SWIFT_SOLR_WAR_FILE='solr.war'
SWIFT_SCHEMA_FILE='schema.xml'
SWIFT_API_BASP_CERTIFICATE='api-basp.che001.com.pem'
SWIFT_RABBITMQ_CERTIFICATE='rabbitmq.che001.com.pem'
SWIFT_TRUSTED_CAROOT_CERTIFICATE='trustApache.jks'
SWIFT_TRUSTED_CAROOT_CERTIFICATE_PEM='accepted_cert_v4.pem'
SWIFT_BANKING_CERTIFICATE='keyC_v4.jks'
SWIFT_ANDROID_CONTAINER='android'
SWIFT_CERTIFICATES_CONTAINER='certificates'
SWIFT_HAPROXY_FILE='haproxy-1.5.1.tar.gz'
SWIFT_HAPROXY_CERTIFICATE='che001.com.pem'
SWIFT_ZAPACHE='zapache.sh'
SWIFT_ZABBIX_HAPROXY_ZIP='zabbix_scripts-master.tar.gz'
SWIFT_REDIS_MONITORING_PYTHON='zbx_redis_stats.py'
SWIFT_MAINTENANCE_PAGE='maintenance.http'
