#!/bin/bash

if [ -z "$1" ]; then
echo "Please enter environment ex. 
		./addlbs.sh stage
		./addlbs.sh prod
		"
exit 1
fi

ENVIRONMENT=$1

. ../utils/config_func.sh
loadConfigParamsLocally $ENVIRONMENT

. parameters

function createHTTPSLoadBalancers(){
./createlb.sh $LB_HTTPS_API_USER $HTTPS_API_USER_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_AUTH $HTTPS_API_AUTH_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_BANKING $HTTPS_API_BANKING_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_COMPANY $HTTPS_API_COMPANY_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_SUPPORT $HTTPS_API_SUPPORT_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_SEARCH $HTTPS_API_SEARCH_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_TRANSACTION $HTTPS_API_TRANSACTION_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_BACKEND $HTTPS_API_BACKEND_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_API_BASP $HTTPS_API_BASP_FLOATING_IP $LB_HTTPS_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlb.sh $LB_HTTPS_WEB_UI $HTTPS_WEBUI_FLOATING_IP $LB_PING_HEALTH_MONITOR 'HTTPS' $ENVIRONMENT
./createlbWithoutFloatingIp.sh $LB_TCP_RABBITMQ $LB_PING_HEALTH_MONITOR 'TCP' $ENVIRONMENT
}

function createHTTPLoadBalancers(){
./createlbWithoutFloatingIp.sh $LB_HTTP_API_USER $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $USER_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_AUTH $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $AUTH_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_BANKING $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $BANKING_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_COMPANY $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $COMPANY_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_SUPPORT $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $SUPPORT_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_SEARCH $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $SEARCH_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_TRANSACTION $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $TRANSACTION_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_BACKEND $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $BACKEND_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_API_BASP $LB_HTTP_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $BASP_LB_IP
./createlbWithoutFloatingIp.sh $LB_HTTP_WEB_UI $LB_PING_HEALTH_MONITOR 'HTTP' $ENVIRONMENT $WEBUI_LB_IP
./createlbWithoutFloatingIp.sh $LB_TCP_RABBITMQ $LB_PING_HEALTH_MONITOR 'TCP' $ENVIRONMENT $RABBITMQ_LB_IP
}

function createAllLoadBalancers(){
#createHTTPSLoadBalancers
createHTTPLoadBalancers

./createlb.sh $LB_HTTP_PROPAGANDA $HTTP_PROPAGANDA_FLOATING_IP $LB_PING_HEALTH_MONITOR 'HTTP' $ENVIRONMENT
./createlb.sh $LB_HTTP_AndroidPromo $HTTP_ANDROID_PROMO_FLOATING_IP $LB_PING_HEALTH_MONITOR 'HTTP' $ENVIRONMENT
}

#createHTTPSLoadBalancers
createHTTPLoadBalancers
#createAllLoadBalancers