#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
echo "Please enter build no, webui build no and environment ex. 
		./addmemberstolb.sh 371 84 stage 
		./addmemberstolb.sh 371 84 prod
		"
exit 1
fi
BUILD_NO=$1
WEBUI_BUILD_NO=$2
ENVIRONMENT=$3

. ../utils/config_func.sh
loadConfigParamsLocally $ENVIRONMENT

. parameters

checkNovaAndNeutron

function searchSimpleMemberIP(){
GENERIC=$1
grep $GENERIC novalist.tmp | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function searchMemberIP(){
GENERIC=$1
MEMBER_NO=$2
grep $GENERIC novalist.tmp | grep '\-'$MEMBER_NO' '  | grep '\-'$BUILD_NO'\-' | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function searchWebuiMemberIP(){
GENERIC=$1
MEMBER_NO=$2
grep $GENERIC novalist.tmp | grep '\-'$MEMBER_NO' '  | grep '\-'$WEBUI_BUILD_NO'\-' | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function formmembers(){
listInstances
AUTH_MEMBER_1=$(searchMemberIP $API_AUTH_GENERIC 01)
USER_MEMBER_1=$(searchMemberIP $API_USER_GENERIC 01) 
BANKING_MEMBER_1=$(searchMemberIP $API_BANKING_GENERIC 01) 
COMPANY_MEMBER_1=$(searchMemberIP $API_COMPANY_GENERIC 01) 
SUPPORT_MEMBER_1=$(searchMemberIP $API_SUPPORT_GENERIC 01) 
SEARCH_MEMBER_1=$(searchMemberIP $API_SEARCH_GENERIC 01) 
TRANSACTION_MEMBER_1=$(searchMemberIP $API_TRANSACTION_GENERIC 01)
BACKEND_MEMBER_1=$(searchMemberIP $API_BACKEND_GENERIC 01)
BASP_MEMBER_1=$(searchMemberIP $API_BASP_GENERIC 01)
WEBUI_MEMBER_1=$(searchWebuiMemberIP $WEBUI_GENERIC 01)

AUTH_MEMBER_2=$(searchMemberIP $API_AUTH_GENERIC 02)
USER_MEMBER_2=$(searchMemberIP $API_USER_GENERIC 02) 
BANKING_MEMBER_2=$(searchMemberIP $API_BANKING_GENERIC 02) 
COMPANY_MEMBER_2=$(searchMemberIP $API_COMPANY_GENERIC 02) 
SUPPORT_MEMBER_2=$(searchMemberIP $API_SUPPORT_GENERIC 02) 
SEARCH_MEMBER_2=$(searchMemberIP $API_SEARCH_GENERIC 02) 
TRANSACTION_MEMBER_2=$(searchMemberIP $API_TRANSACTION_GENERIC 02)
BACKEND_MEMBER_2=$(searchMemberIP $API_BACKEND_GENERIC 02)
BASP_MEMBER_2=$(searchMemberIP $API_BASP_GENERIC 02)
WEBUI_MEMBER_2=$(searchWebuiMemberIP $WEBUI_GENERIC 02)

PROPAGANDA_MEMBER=$(searchSimpleMemberIP $PROPAGANDA_GENERIC)

}

function addMember(){
PORT_TO_ADD=$1
LB_TO_ADD=$2
MEMBER_TO_ADD=$3

if [ ! -z "$MEMBER_TO_ADD" ]; then
	logMessageToConsole "INFO" "Adding member $MEMBER_TO_ADD to $LB_TO_ADD on port $PORT_TO_ADD"
	neutron lb-member-create --protocol-port $PORT_TO_ADD --address $MEMBER_TO_ADD $LB_TO_ADD > /dev/null
	logMessageToConsole "INFO" "$(neutron lb-member-list | grep $MEMBER_TO_ADD)"
fi
}

function addHTTPSMembersToLoadBalancers(){
formmembers
addMember $PORT_HTTPS_API_AUTH $LB_HTTPS_API_AUTH $AUTH_MEMBER_1
addMember $PORT_HTTPS_API_USER $LB_HTTPS_API_USER $USER_MEMBER_1
addMember $PORT_HTTPS_API_BANKING $LB_HTTPS_API_BANKING $BANKING_MEMBER_1
addMember $PORT_HTTPS_API_COMPANY $LB_HTTPS_API_COMPANY $COMPANY_MEMBER_1
addMember $PORT_HTTPS_API_SUPPORT $LB_HTTPS_API_SUPPORT $SUPPORT_MEMBER_1
addMember $PORT_HTTPS_API_SEARCH $LB_HTTPS_API_SEARCH $SEARCH_MEMBER_1
addMember $PORT_HTTPS_API_TRANSACTION $LB_HTTPS_API_TRANSACTION $TRANSACTION_MEMBER_1
addMember $PORT_HTTPS_API_BACKEND $LB_HTTPS_API_BACKEND $BACKEND_MEMBER_1
addMember $PORT_HTTPS_API_BASP $LB_HTTPS_API_BASP $BASP_MEMBER_1
addMember $PORT_HTTPS_WEBUI $LB_HTTPS_WEB_UI $WEBUI_MEMBER_1

addMember $PORT_HTTPS_API_AUTH $LB_HTTPS_API_AUTH $AUTH_MEMBER_2
addMember $PORT_HTTPS_API_USER $LB_HTTPS_API_USER $USER_MEMBER_2
addMember $PORT_HTTPS_API_BANKING $LB_HTTPS_API_BANKING $BANKING_MEMBER_2
addMember $PORT_HTTPS_API_COMPANY $LB_HTTPS_API_COMPANY $COMPANY_MEMBER_2
addMember $PORT_HTTPS_API_SUPPORT $LB_HTTPS_API_SUPPORT $SUPPORT_MEMBER_2
addMember $PORT_HTTPS_API_SEARCH $LB_HTTPS_API_SEARCH $SEARCH_MEMBER_2
addMember $PORT_HTTPS_API_TRANSACTION $LB_HTTPS_API_TRANSACTION $TRANSACTION_MEMBER_2
addMember $PORT_HTTPS_API_BACKEND $LB_HTTPS_API_BACKEND $BACKEND_MEMBER_2
addMember $PORT_HTTPS_API_BASP $LB_HTTPS_API_BASP $BASP_MEMBER_2
addMember $PORT_HTTPS_WEBUI $LB_HTTPS_WEB_UI $WEBUI_MEMBER_2
}

function addHTTPMembersToLoadBalancers(){
formmembers
addMember $PORT_HTTP_API_AUTH $LB_HTTP_API_AUTH $AUTH_MEMBER_1
addMember $PORT_HTTP_API_USER $LB_HTTP_API_USER $USER_MEMBER_1
addMember $PORT_HTTP_API_BANKING $LB_HTTP_API_BANKING $BANKING_MEMBER_1
addMember $PORT_HTTP_API_COMPANY $LB_HTTP_API_COMPANY $COMPANY_MEMBER_1
addMember $PORT_HTTP_API_SUPPORT $LB_HTTP_API_SUPPORT $SUPPORT_MEMBER_1
addMember $PORT_HTTP_API_SEARCH $LB_HTTP_API_SEARCH $SEARCH_MEMBER_1
addMember $PORT_HTTP_API_TRANSACTION $LB_HTTP_API_TRANSACTION $TRANSACTION_MEMBER_1
addMember $PORT_HTTP_API_BACKEND $LB_HTTP_API_BACKEND $BACKEND_MEMBER_1
addMember $PORT_HTTP_API_BASP $LB_HTTP_API_BASP $BASP_MEMBER_1
addMember $PORT_HTTP_WEBUI $LB_HTTP_WEB_UI $WEBUI_MEMBER_1

addMember $PORT_HTTP_API_AUTH $LB_HTTP_API_AUTH $AUTH_MEMBER_2
addMember $PORT_HTTP_API_USER $LB_HTTP_API_USER $USER_MEMBER_2
addMember $PORT_HTTP_API_BANKING $LB_HTTP_API_BANKING $BANKING_MEMBER_2
addMember $PORT_HTTP_API_COMPANY $LB_HTTP_API_COMPANY $COMPANY_MEMBER_2
addMember $PORT_HTTP_API_SUPPORT $LB_HTTP_API_SUPPORT $SUPPORT_MEMBER_2
addMember $PORT_HTTP_API_SEARCH $LB_HTTP_API_SEARCH $SEARCH_MEMBER_2
addMember $PORT_HTTP_API_TRANSACTION $LB_HTTP_API_TRANSACTION $TRANSACTION_MEMBER_2
addMember $PORT_HTTP_API_BACKEND $LB_HTTP_API_BACKEND $BACKEND_MEMBER_2
addMember $PORT_HTTP_API_BASP $LB_HTTP_API_BASP $BASP_MEMBER_2
addMember $PORT_HTTP_WEBUI $LB_HTTP_WEB_UI $WEBUI_MEMBER_2
}

function addALLMembersToLoadBalancers(){
formmembers
#addHTTPSMembersToLoadBalancers
addHTTPMembersToLoadBalancers

addMember $PORT_HTTP_ANDROID_PROMO $LB_HTTP_AndroidPromo $PROPAGANDA_MEMBER
addMember $PORT_HTTP_PROPAGANDA $LB_HTTP_PROPAGANDA $PROPAGANDA_MEMBER
}

######################run main######################
#addHTTPSMembersToLoadBalancers
addHTTPMembersToLoadBalancers
#addALLMembersToLoadBalancers
clean
