#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
echo "Please enter build no, webui build no and environment ex. ./maplbmembers.sh 371 84 prod | ./maplbmembers.sh 371 84 stage"
exit 1
fi
BUILD_NO=$1
WEBUI_BUILD_NO=$2
ENVIRONMENT=$3

. ../utils/config_func.sh
loadConfigParamsLocally $ENVIRONMENT

. parameters

checkNovaAndNeutron

function searchSimpleMemberIP(){
GENERIC=$1
MEMBER_NO=$2
grep $GENERIC novalist.tmp | grep '\-'$MEMBER_NO' '  | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function searchMemberIP(){
GENERIC=$1
MEMBER_NO=$2
grep $GENERIC novalist.tmp | grep '\-'$MEMBER_NO' '  | grep '\-'$BUILD_NO'\-' | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function searchWebuiMemberIP(){
GENERIC=$1
MEMBER_NO=$2
grep $GENERIC novalist.tmp | grep '\-'$MEMBER_NO' '  | grep '\-'$WEBUI_BUILD_NO'\-' | awk -F'|' '{print $7}' | awk -F'=' '{print $2}' | awk -F',' '{ print $1 }' | tr -d ' '
}

function displayWarningOrErrorOnInstances(){
INST_TYPE=$1
MEMB1=$2
MEMB2=$3
if [ -z "$MEMB1" -a -z "$MEMB2" ]; then
	echo 'ERROR: no instance was found for build '$BUILD_NO' on '$INST_TYPE
elif [ -z "$MEMB1" -o -z "$MEMB2" ]; then
	echo 'WARNING: only one instance was found for build '$BUILD_NO' on '$INST_TYPE
fi
}

function displayWarningOrErrorOnInstancesWebui(){
INST_TYPE=$1
MEMB1=$2
MEMB2=$3
if [ -z "$MEMB1" -a -z "$MEMB2" ]; then
	echo 'ERROR: no instance was found for build '$BUILD_NO' on '$INST_TYPE
elif [ -z "$MEMB1" -o -z "$MEMB2" ]; then
	echo 'WARNING: only one instance was found for build '$WEBUI_BUILD_NO' on '$INST_TYPE
fi
}

function displayWarningsOnInstances(){
displayWarningOrErrorOnInstances $API_AUTH_GENERIC $AUTH_MEMBER_IP_1 $AUTH_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_USER_GENERIC $USER_MEMBER_IP_1 $USER_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_BANKING_GENERIC $BANKING_MEMBER_IP_1 $BANKING_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_COMPANY_GENERIC $COMPANY_MEMBER_IP_1 $COMPANY_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_SUPPORT_GENERIC $SUPPORT_MEMBER_IP_1 $SUPPORT_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_SEARCH_GENERIC $SEARCH_MEMBER_IP_1 $SEARCH_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_TRANSACTION_GENERIC $TRANSACTION_MEMBER_IP_1 $TRANSACTION_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_BACKEND_GENERIC $BACKEND_MEMBER_IP_1 $BACKEND_MEMBER_IP_2
displayWarningOrErrorOnInstances $API_BASP_GENERIC $BASP_MEMBER_IP_1 $BASP_MEMBER_IP_2
displayWarningOrErrorOnInstancesWebui $WEBUI_GENERIC $WEBUI_MEMBER_IP_1 $WEBUI_MEMBER_IP_2
}

function formMembersIPs(){
listInstances

PROPAGANDA_MEMBER_IP=$(searchSimpleMemberIP $PROPAGANDA_GENERIC 01)

AUTH_MEMBER_IP_1=$(searchMemberIP $API_AUTH_GENERIC 01)
USER_MEMBER_IP_1=$(searchMemberIP $API_USER_GENERIC 01) 
BANKING_MEMBER_IP_1=$(searchMemberIP $API_BANKING_GENERIC 01) 
COMPANY_MEMBER_IP_1=$(searchMemberIP $API_COMPANY_GENERIC 01) 
SUPPORT_MEMBER_IP_1=$(searchMemberIP $API_SUPPORT_GENERIC 01) 
SEARCH_MEMBER_IP_1=$(searchMemberIP $API_SEARCH_GENERIC 01) 
TRANSACTION_MEMBER_IP_1=$(searchMemberIP $API_TRANSACTION_GENERIC 01)
BACKEND_MEMBER_IP_1=$(searchMemberIP $API_BACKEND_GENERIC 01)
BASP_MEMBER_IP_1=$(searchMemberIP $API_BASP_GENERIC 01)
WEBUI_MEMBER_IP_1=$(searchWebuiMemberIP $WEBUI_GENERIC 01)

AUTH_MEMBER_IP_2=$(searchMemberIP $API_AUTH_GENERIC 02)
USER_MEMBER_IP_2=$(searchMemberIP $API_USER_GENERIC 02) 
BANKING_MEMBER_IP_2=$(searchMemberIP $API_BANKING_GENERIC 02) 
COMPANY_MEMBER_IP_2=$(searchMemberIP $API_COMPANY_GENERIC 02) 
SUPPORT_MEMBER_IP_2=$(searchMemberIP $API_SUPPORT_GENERIC 02) 
SEARCH_MEMBER_IP_2=$(searchMemberIP $API_SEARCH_GENERIC 02) 
TRANSACTION_MEMBER_IP_2=$(searchMemberIP $API_TRANSACTION_GENERIC 02)
BACKEND_MEMBER_IP_2=$(searchMemberIP $API_BACKEND_GENERIC 02)
BASP_MEMBER_IP_2=$(searchMemberIP $API_BASP_GENERIC 02)
WEBUI_MEMBER_IP_2=$(searchWebuiMemberIP $WEBUI_GENERIC 02)
displayWarningsOnInstances

}


function searchLBMember(){
PORT=$1
MEMBER_IP=$2
if [ ! -z "$MEMBER_IP" ]; then
grep $MEMBER_IP memberlist.tmp | grep $PORT | awk -F'|' '{ print $2 }' | tr -d ' '
fi
}

function displayWarningOrErrorOnMembers(){
INST_TYPE=$1
MEMB1=$2
MEMB2=$3
if [ ! -z "$MEMB2" -a -z "$MEMB1" ]; then
	echo 'WARNING: instance with build: '$BUILD_NO' on '$INST_TYPE' exists but is not added to lb'
fi
}

function displayWarningOrErrorOnMembersWebui(){
INST_TYPE=$1
MEMB1=$2
MEMB2=$3
if [ ! -z "$MEMB2" -a -z "$MEMB1" ]; then
	echo 'WARNING: instance with build: '$WEBUI_BUILD_NO' on '$INST_TYPE' exists but is not added to lb'
fi
}

function displayWarningsOnMembersHTTPS(){
displayWarningOrErrorOnMembers	$API_AUTH_GENERIC	$AUTH_HTTPS_MEMBER_1	$AUTH_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_USER_GENERIC	$USER_HTTPS_MEMBER_1	$USER_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BANKING_GENERIC	$BANKING_HTTPS_MEMBER_1	$BANKING_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_COMPANY_GENERIC	$COMPANY_HTTPS_MEMBER_1	$COMPANY_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_SUPPORT_GENERIC	$SUPPORT_HTTPS_MEMBER_1	$SUPPORT_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_SEARCH	$SEARCH_HTTPS_MEMBER_1	$SEARCH_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_TRANSACTION_GENERIC	$TRANSACTION_HTTPS_MEMBER_1	$TRANSACTION_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BACKEND_GENERIC	$BACKEND_HTTPS_MEMBER_1	$BACKEND_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BASP_GENERIC	$BASP_HTTPS_MEMBER_1	$BASP_MEMBER_IP_1
displayWarningOrErrorOnMembersWebui	$WEBUI_GENERIC	$WEBUI_HTTPS_MEMBER_1	$WEBUI_MEMBER_IP_1

displayWarningOrErrorOnMembers	$API_AUTH_GENERIC	$AUTH_HTTPS_MEMBER_2	$AUTH_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_USER_GENERIC	$USER_HTTPS_MEMBER_2	$USER_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BANKING_GENERIC	$BANKING_HTTPS_MEMBER_2	$BANKING_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_COMPANY_GENERIC	$COMPANY_HTTPS_MEMBER_2	$COMPANY_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_SUPPORT_GENERIC	$SUPPORT_HTTPS_MEMBER_2	$SUPPORT_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_SEARCH	$SEARCH_HTTPS_MEMBER_2	$SEARCH_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_TRANSACTION_GENERIC	$TRANSACTION_HTTPS_MEMBER_2	$TRANSACTION_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BACKEND_GENERIC	$BACKEND_HTTPS_MEMBER_2	$BACKEND_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BASP_GENERIC	$BASP_HTTPS_MEMBER_2	$BASP_MEMBER_IP_2
displayWarningOrErrorOnMembersWebui	$WEBUI_GENERIC	$WEBUI_HTTPS_MEMBER_2	$WEBUI_MEMBER_IP_2
}

function displayWarningsOnMembersHTTP(){
displayWarningOrErrorOnMembers	$API_AUTH_GENERIC	$AUTH_HTTP_MEMBER_1	$AUTH_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_USER_GENERIC	$USER_HTTP_MEMBER_1	$USER_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BANKING_GENERIC	$BANKING_HTTP_MEMBER_1	$BANKING_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_COMPANY_GENERIC	$COMPANY_HTTP_MEMBER_1	$COMPANY_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_SUPPORT_GENERIC	$SUPPORT_HTTP_MEMBER_1	$SUPPORT_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_SEARCH	$SEARCH_HTTP_MEMBER_1	$SEARCH_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_TRANSACTION_GENERIC	$TRANSACTION_HTTP_MEMBER_1	$TRANSACTION_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BACKEND_GENERIC	$BACKEND_HTTP_MEMBER_1	$BACKEND_MEMBER_IP_1
displayWarningOrErrorOnMembers	$API_BASP_GENERIC	$BASP_HTTP_MEMBER_1	$BASP_MEMBER_IP_1
displayWarningOrErrorOnMembersWebui $WEBUI_GENERIC	$WEBUI_HTTP_MEMBER_1	$WEBUI_MEMBER_IP_1

displayWarningOrErrorOnMembers	$API_AUTH_GENERIC	$AUTH_HTTP_MEMBER_2	$AUTH_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_USER_GENERIC	$USER_HTTP_MEMBER_2	$USER_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BANKING_GENERIC	$BANKING_HTTP_MEMBER_2	$BANKING_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_COMPANY_GENERIC	$COMPANY_HTTP_MEMBER_2	$COMPANY_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_SUPPORT_GENERIC	$SUPPORT_HTTP_MEMBER_2	$SUPPORT_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_SEARCH	$SEARCH_HTTP_MEMBER_2	$SEARCH_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_TRANSACTION_GENERIC	$TRANSACTION_HTTP_MEMBER_2	$TRANSACTION_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BACKEND_GENERIC	$BACKEND_HTTP_MEMBER_2	$BACKEND_MEMBER_IP_2
displayWarningOrErrorOnMembers	$API_BASP_GENERIC	$BASP_HTTP_MEMBER_2	$BASP_MEMBER_IP_2
displayWarningOrErrorOnMembersWebui $WEBUI_GENERIC	$WEBUI_HTTP_MEMBER_2	$WEBUI_MEMBER_IP_2
}

function findHTTPSMembers(){
ANDROID_PROMO_HTTP_MEMBER=$(searchLBMember $PORT_HTTP_ANDROID_PROMO $PROPAGANDA_MEMBER_IP)
PROPAGANDA_HTTP_MEMBER=$(searchLBMember $PORT_HTTP_PROPAGANDA $PROPAGANDA_MEMBER_IP)  

AUTH_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_AUTH $AUTH_MEMBER_IP_1)
USER_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_USER $USER_MEMBER_IP_1) 
BANKING_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_BANKING $BANKING_MEMBER_IP_1) 
COMPANY_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_COMPANY $COMPANY_MEMBER_IP_1) 
SUPPORT_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_SUPPORT $SUPPORT_MEMBER_IP_1) 
SEARCH_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_SEARCH $SEARCH_MEMBER_IP_1) 
TRANSACTION_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_TRANSACTION $TRANSACTION_MEMBER_IP_1) 
BACKEND_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_BACKEND $BACKEND_MEMBER_IP_1) 
BASP_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_API_BASP $BASP_MEMBER_IP_1)
WEBUI_HTTPS_MEMBER_1=$(searchLBMember $PORT_HTTPS_WEBUI $WEBUI_MEMBER_IP_1) 

AUTH_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_AUTH $AUTH_MEMBER_IP_2)
USER_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_USER $USER_MEMBER_IP_2) 
BANKING_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_BANKING $BANKING_MEMBER_IP_2) 
COMPANY_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_COMPANY $COMPANY_MEMBER_IP_2) 
SUPPORT_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_SUPPORT $SUPPORT_MEMBER_IP_2) 
SEARCH_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_SEARCH $SEARCH_MEMBER_IP_2) 
TRANSACTION_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_TRANSACTION $TRANSACTION_MEMBER_IP_2) 
BACKEND_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_BACKEND $BACKEND_MEMBER_IP_2)
BASP_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_API_BASP $BASP_MEMBER_IP_2)
WEBUI_HTTPS_MEMBER_2=$(searchLBMember $PORT_HTTPS_WEBUI $WEBUI_MEMBER_IP_2) 

displayWarningsOnMembersHTTPS
}

function findHTTPMembers(){
ANDROID_PROMO_HTTP_MEMBER=$(searchLBMember $PORT_HTTP_ANDROID_PROMO $PROPAGANDA_MEMBER_IP)
PROPAGANDA_HTTP_MEMBER=$(searchLBMember $PORT_HTTP_PROPAGANDA $PROPAGANDA_MEMBER_IP)  

AUTH_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_AUTH $AUTH_MEMBER_IP_1)
USER_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_USER $USER_MEMBER_IP_1) 
BANKING_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_BANKING $BANKING_MEMBER_IP_1) 
COMPANY_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_COMPANY $COMPANY_MEMBER_IP_1) 
SUPPORT_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_SUPPORT $SUPPORT_MEMBER_IP_1) 
SEARCH_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_SEARCH $SEARCH_MEMBER_IP_1) 
TRANSACTION_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_TRANSACTION $TRANSACTION_MEMBER_IP_1) 
BACKEND_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_BACKEND $BACKEND_MEMBER_IP_1)
BASP_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_API_BASP $BASP_MEMBER_IP_1)
WEBUI_HTTP_MEMBER_1=$(searchLBMember $PORT_HTTP_WEBUI $WEBUI_MEMBER_IP_1) 

AUTH_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_AUTH $AUTH_MEMBER_IP_2)
USER_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_USER $USER_MEMBER_IP_2) 
BANKING_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_BANKING $BANKING_MEMBER_IP_2) 
COMPANY_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_COMPANY $COMPANY_MEMBER_IP_2) 
SUPPORT_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_SUPPORT $SUPPORT_MEMBER_IP_2) 
SEARCH_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_SEARCH $SEARCH_MEMBER_IP_2) 
TRANSACTION_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_TRANSACTION $TRANSACTION_MEMBER_IP_2) 
BACKEND_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_BACKEND $BACKEND_MEMBER_IP_2)
BASP_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_API_BASP $BASP_MEMBER_IP_2)
WEBUI_HTTP_MEMBER_2=$(searchLBMember $PORT_HTTP_WEBUI $WEBUI_MEMBER_IP_2) 

displayWarningsOnMembersHTTP
}

function findmembers(){
formMembersIPs
listMembers

#findHTTPSMembers
findHTTPMembers
}


######################run main######################
findmembers